[build]
  # Perintah build yang sama dengan yang ada di package.json Anda
  command = "npm run build"
  # Direktori output Next.js
  publish = ".next"

[dev]
  # Menentukan Next.js sebagai framework pengembangan
  framework = "next" 
  command = "npm run dev"

# Tambahkan variabel lingkungan untuk menonaktifkan ESLint selama proses build Netlify
[build.environment]
  # Matikan plugin ESLint (untuk menghindari error ERESOLVE saat build)
  DISABLE_ESLINT_PLUGIN = "true" 
  # Matikan peringatan yang mungkin muncul dari TypeScript/ESLint
  ESLINT_NO_DEV_ERRORS = "true"


[[plugins]]
  package = "@netlify/plugin-nextjs"